[[MPIABI]]
arch = "aarch64"
git-tree-sha1 = "b1d9263055895d5a595fdb6a2cc6170927365d17"
lazy = true
mpi = "mpiabi"
os = "macos"

    [[MPIABI.download]]
    sha256 = "0980d7ad20f5d38c26e5f63d4bc5068f76e5c2bbcdbd06192103f9bd0cb9496c"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v1.0.0+0/MPIABI.v1.0.0.aarch64-apple-darwin-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "aarch64"
git-tree-sha1 = "a044bd5f5fd81133bf24daa1eb6a645824cbd809"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "b98eda8c7d4bef75590334268b99702dd964bae3daad26be777b381f7219c1ed"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v1.0.0+0/MPIABI.v1.0.0.aarch64-linux-gnu-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "aarch64"
git-tree-sha1 = "93d70e78fc23ac582510942138c1a7e675904184"
lazy = true
libc = "musl"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "a1ded28fe14ee3c670d4bd77e4c765f16dcb4ec3016e69e0e966f56387e0166d"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v1.0.0+0/MPIABI.v1.0.0.aarch64-linux-musl-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "aarch64"
git-tree-sha1 = "47b4d2f458b6fdbbe936a70cdb86e56b7cfd3135"
lazy = true
mpi = "mpiabi"
os = "freebsd"

    [[MPIABI.download]]
    sha256 = "f84a8f4ebf699550cdaa9f0a246b9b0bf0677ea4f694a4c1756447220b610ab2"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v1.0.0+0/MPIABI.v1.0.0.aarch64-unknown-freebsd-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "29b6e207c9194ae6e59aeacd4e178b5fcea1eb5f"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "3e263587e7f644c9e8e86e64c0055b386683a7bcd89ec2c221bba768444d7348"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v1.0.0+0/MPIABI.v1.0.0.armv6l-linux-gnueabihf-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0d328ffbc90b38984b9b1c2f0149fdad4549f5a1"
lazy = true
libc = "musl"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "20a3c13ab254248d9b01c574286affb3c2c993cea5da909134008c9eae9afd9b"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v1.0.0+0/MPIABI.v1.0.0.armv6l-linux-musleabihf-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "715b3966fcb2436b27b3456f0100bf248378fa72"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "37f2703bfdbab3223de3dec368dc4e926cdca4de0770364b760c3c87b543a4c1"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v1.0.0+0/MPIABI.v1.0.0.armv7l-linux-gnueabihf-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "61ec653f84886e83f9c33179537c7a3653d7fa00"
lazy = true
libc = "musl"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "76756973c843d0a370780f71528d5b9ae6b3ce4ac4428233b3c09fde16435781"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v1.0.0+0/MPIABI.v1.0.0.armv7l-linux-musleabihf-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "i686"
git-tree-sha1 = "1feaf81fabb49965011dc55680ab26a93d6826cf"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "b91d520d58b8666aa7ad11b71de723b48ed1c0589ff24d81661054fbd1fa7e66"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v1.0.0+0/MPIABI.v1.0.0.i686-linux-gnu-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "i686"
git-tree-sha1 = "74d48be810c2c2b3701bc5d751d93f531ab4bf5c"
lazy = true
libc = "musl"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "63cc642b309b8770e257cea34c13fdc73d88ecba7a2d8b7b831ad41e9875dd00"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v1.0.0+0/MPIABI.v1.0.0.i686-linux-musl-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "powerpc64le"
git-tree-sha1 = "432f729ef3fb48837b723f7fd3c9a6e0afe36644"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "b11fa90a715325e65593013ac9b4bd1eed7bab8286e9bb8d9738a770a9021e21"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v1.0.0+0/MPIABI.v1.0.0.powerpc64le-linux-gnu-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "riscv64"
git-tree-sha1 = "dcbb3baaa2d5e62b3082c4b1abead722fe96195b"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "8e1c6a95edef0b40684c746ea714af323339dc3c1fda385bc65e39c595a31756"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v1.0.0+0/MPIABI.v1.0.0.riscv64-linux-gnu-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "x86_64"
git-tree-sha1 = "68fb17e6761dea1e0463f0a7217d6708efc241e4"
lazy = true
mpi = "mpiabi"
os = "macos"

    [[MPIABI.download]]
    sha256 = "69af4db1ab3a416c67475a8ce7cdd98e8d99ac7e97978312ab4e2e161c8532a2"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v1.0.0+0/MPIABI.v1.0.0.x86_64-apple-darwin-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "x86_64"
git-tree-sha1 = "713307f3452c8658115ca784e1597fd12010e9c9"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "8c1e3ae505c3eebb004f8c984b580477377a8fe25492c840bbf16a833305616b"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v1.0.0+0/MPIABI.v1.0.0.x86_64-linux-gnu-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "x86_64"
git-tree-sha1 = "07f17df6c97555e66e62ef864d50cde50eb3d10e"
lazy = true
libc = "musl"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "d51a83cafed62ea8305f026695c58d4d970a77ec00d01774fac3cd823b128f0b"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v1.0.0+0/MPIABI.v1.0.0.x86_64-linux-musl-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "x86_64"
git-tree-sha1 = "19331510a18ae18ebc80c5cbc535d21168d96e82"
lazy = true
mpi = "mpiabi"
os = "freebsd"

    [[MPIABI.download]]
    sha256 = "f765b399b48c3ea7e1693afd0c29ddab882533dbfcc1b3c2ec0526b665bf1c28"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v1.0.0+0/MPIABI.v1.0.0.x86_64-unknown-freebsd-mpi+mpiabi.tar.gz"
