[[MPIABI]]
arch = "aarch64"
git-tree-sha1 = "8692adb4bad4d72f8a0d41ab8dc54eebd46ac0f2"
lazy = true
mpi = "mpiabi"
os = "macos"

    [[MPIABI.download]]
    sha256 = "e5f92c55a757b3f273fe73b05492e7880a69e3666ebb88fcfe6067e0e83e56aa"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.1+1/MPIABI.v0.1.1.aarch64-apple-darwin-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "aarch64"
git-tree-sha1 = "2c6f626bbb156c4e7598b80e6376089b3a5f20a8"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "0429cba00421b1ea6ded5ff7ef94979a7170484aad37df1affc702d2a04344d7"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.1+1/MPIABI.v0.1.1.aarch64-linux-gnu-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "aarch64"
git-tree-sha1 = "e9e422af59a2f9a8cdd99607545fcd5f5e1ab96b"
lazy = true
libc = "musl"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "23527227e6e88b2641db7507b7669008a34ca6227d40d927ce13161fefaf39e8"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.1+1/MPIABI.v0.1.1.aarch64-linux-musl-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "aarch64"
git-tree-sha1 = "bfc2549b6132578f26d8c918d810d0a8e920adb5"
lazy = true
mpi = "mpiabi"
os = "freebsd"

    [[MPIABI.download]]
    sha256 = "1e819d04960c43527e34c40f5570bfbdc35231e612953127b73d2c8171705927"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.1+1/MPIABI.v0.1.1.aarch64-unknown-freebsd-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d703c290e285a4275ba5af157627ea1156378550"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "b2f35c58b0df734fabcce2e0ce76f532302b25abccb536f7000dc8b404492922"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.1+1/MPIABI.v0.1.1.armv6l-linux-gnueabihf-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c3ff46e08abb443a32bb92d924264f063e47e842"
lazy = true
libc = "musl"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "e28ca079950d5970b333388160bf7f355591a7ef86fea2f2fff7e472f929b95d"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.1+1/MPIABI.v0.1.1.armv6l-linux-musleabihf-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c3389af21db64b4332e1b6dbd2a97b26563fae68"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "4a1b395cfdb18d1cfe144e9c819f3abf8a94ff7af04b5f983bd67bf88e03e1cf"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.1+1/MPIABI.v0.1.1.armv7l-linux-gnueabihf-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "858c9a9462156484b70b4ecfa82a1eda6ff68116"
lazy = true
libc = "musl"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "24794e0baa3ada8a9fadfddf20082d41e1d87dce5bce7f75452ae6a795398361"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.1+1/MPIABI.v0.1.1.armv7l-linux-musleabihf-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "i686"
git-tree-sha1 = "cb871a305e69096282e71f521cebc18e0fcc30a3"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "223193f8853ffd2b8979fcf04443f8921acbc425debb79c3f8566fe14f578959"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.1+1/MPIABI.v0.1.1.i686-linux-gnu-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "i686"
git-tree-sha1 = "7265b0b6a31943e0c4e6cd75bca80561f3e1d49a"
lazy = true
libc = "musl"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "2b9e98a0754d6672444825555c365ab7bd3ed6304ace5f1b38b32d7f1c3cca35"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.1+1/MPIABI.v0.1.1.i686-linux-musl-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "powerpc64le"
git-tree-sha1 = "b0cf0253770ab74a372081161a2d9762fdd5acd5"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "89db9021d632fa8f5ca557cb19c42b03a94a3716865c36bcf140d3b6e976de5f"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.1+1/MPIABI.v0.1.1.powerpc64le-linux-gnu-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "riscv64"
git-tree-sha1 = "6e2dce46eec66cedaf30e705d30392b8be54e0a6"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "a279d399151bdd749aa94d07d15822c85a59b5ff5a8c7eb43fe033892eaabc59"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.1+1/MPIABI.v0.1.1.riscv64-linux-gnu-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "x86_64"
git-tree-sha1 = "612461356b599fcf8f90891b435eed62bac3c802"
lazy = true
mpi = "mpiabi"
os = "macos"

    [[MPIABI.download]]
    sha256 = "1ca7c78ce8e09a67389556029638d84fbba7b2e7552a7440281b99e9d61c3fa9"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.1+1/MPIABI.v0.1.1.x86_64-apple-darwin-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "x86_64"
git-tree-sha1 = "a125e2722059724c570c12c959145c33a8eb45a0"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "4205887762afa1ec495532fbe101d4499c6cf41faf7db26a8b9e85ba5b5ebd13"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.1+1/MPIABI.v0.1.1.x86_64-linux-gnu-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "x86_64"
git-tree-sha1 = "c8d6b52d89eac88becb69bf438b8e6ee4320a56e"
lazy = true
libc = "musl"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "d11e0fb08c3ba0ee87ddbd0283f218c03069a2e505dcc8109d543bd5dd80694a"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.1+1/MPIABI.v0.1.1.x86_64-linux-musl-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "x86_64"
git-tree-sha1 = "dc0454347e0422aa4ff4d8ebbe608a14f0a7aca7"
lazy = true
mpi = "mpiabi"
os = "freebsd"

    [[MPIABI.download]]
    sha256 = "30475d1a8029f9b0a77cd01bf63533f2319057a04eff5480fccb38305ec5a329"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.1+1/MPIABI.v0.1.1.x86_64-unknown-freebsd-mpi+mpiabi.tar.gz"
